# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: postgres-presensi-app
    image: 'postgres:10.11'
    volumes:
      - 'postgres-data-presensi-app:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  postgres-data-presensi-app: null

